### ISSUE TITLE
Should require userOptions

### ISSUE THREAD

**Issue by ghutchis** [research11111/biodeg-avogadro-plugin#1]
In principle, Avogadro shouldn't require the `userOptions` part, e.g. https://github.com/OpenChemistry/avogadro-commands/blob/master/flattenZ.py

In that case, the script should just run without a dialog.

If that doesn't work, please file an issue at `avogadrolibs` - I can imagine lots of cases like this plugin that don't require user options.

I'm also curious for feedback on your tool - would it be easier if computed properties like this go into the "Molecular Properties" dialog. For example, the plugin returns:

```
{
"properties": { "biodegradability": "{result}" }
}
```

That triggers Avogadro to add "biodegradability" to the properties dialog and possibly open it.

You may still want the PyQt interface, but I can imagine a lot of plugins that compute properties, XY plots, etc. (solubility, logP, …)

I would be happy to discuss more, e.g. https://discuss.avogadro.cc

**Comment by ghutchis** [comment]
By the way, this looks great - I'm very happy to see others take up the plugin scripts. 🚀

**Comment by research11111** [comment]
With mordred lib there is indeed many molecular descriptors possible

**Comment by research11111** [comment]
Could be a nice feature so what you propose is a new extension point to avogadro eg "molecular properties scripts".

possibilities on thoses scripts:
 - add multiple properties to the "molecular properties" dialog
 - computation on molecules when openning the popup or as background task (eg when user do not change the molecule for a while)
 - direct link mordred descriptor to the dialog

I would be happy to test the api if you write for that

**Comment by ghutchis** [comment]
That's a good point a "properties" script type that was called whenever the molecule changes (and killed if the molecule changes before the calculation is finished).

I guess it would be useful to separate changes for 0D / 2D descriptors vs. 3D descriptors.

Do you think these scripts would need filtering based on elements / unit cells, etc.?

**Comment by ghutchis** [comment]
FYI - https://github.com/OpenChemistry/avogadrolibs/issues/1439
